### ISSUE TITLE
Update to latest Indy SDK

### ISSUE THREAD

**Issue by ianco** [openwallet-foundation/bifold-wallet#127] opened 2021-11-10 19:05 UTC
In AFJ the indy sdk reference (in package.json) is:

`"indy-sdk": "^1.16.0-dev-1636",`

Bifold looks like it's still on `1.14.0`, can we update to the latest Indy SDK?

**Comment by TimoGlastra** [comment] 2021-11-11 08:21
To be honest that is easier said than done. The build pipeline for indy is quite broken and therefore not so easily updated. Android may be easier that iOS, but it took us a really long time to figure out how to build the `Indy.Framework` that is now in this repo. 

See https://github.com/AbsaOSS/rn-indy-sdk/issues/20 for more info. In the end I was able to build it using this repo: https://github.com/riccardocaranfil/libindy-pod 

If you want to give it a shot I will be happy to guide you with what we already know! 

We're currently sticking with Indy as is, and will invest our efforts in the new shared libraries

**Comment by ianco** [comment] 2021-11-11 13:41
@TimoGlastra thanks for the info.

**Comment by jleach** [comment] 2022-07-21 18:18
Duplicate of #156.

**Closed as completed by jleach** 2022-07-21 18:18 UTC
